apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260624-135111-5pxrn4o97nxe-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260624-135111-5pxrn4o97nxe.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260624-135111-5pxrn4o97nxe-service
            port:
              number: 80
