apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260624-135111-5pxrn4o97nxe-service
spec:
  selector:
    app: enterprise-system-20260624-135111-5pxrn4o97nxe
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
